### ISSUE TITLE
User gid: 911

### ISSUE THREAD

**Issue by Howard-Shao** [TonyRL/docker-transmission-skip-hash-check#11]
使用-e PGID=1000之后，容器运行还是User gid: 911，导致在2.94升级3.00过程中，对downloads文件夹权限出错，容器不能正确启动。bionic-v3、focal/latest两个版本均出现这样的问题，同样的设置更换linuxserver的3.0版本无问题。
基础环境：unraid6.8       docker版本：19.03.5

Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid: 1000
User gid: 911
-------------------------------------

cont-init: info: /etc/cont-init.d/10-adduser exited 0
cont-init: info: running /etc/cont-init.d/20-config
cont-init: info: /etc/cont-init.d/20-config exited 0
cont-init: info: running /etc/cont-init.d/90-custom-folders
cont-init: info: /etc/cont-init.d/90-custom-folders exited 0
cont-init: info: running /etc/cont-init.d/99-custom-scripts
[custom-init] no custom files found exiting...
cont-init: info: /etc/cont-init.d/99-custom-scripts exited 0

**Comment by TonyRL** [comment]
You are advised to stick with default PUID and PGID which are 99 and 100 respectively.

https://github.com/linuxserver/templates/blob/26f98e49084c2c2fae87bb02bcc41c4d0a755791/unraid/transmission.xml#L145-L146

**Comment by Howard-Shao** [comment]
> 

很抱歉，检查了下，是我自己的设置问题，容器正常的。
谢谢您的回复~
